---
abstract: 'Add Test::DiagINC to all .t files'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Spec::Functions: 0
  List::Util: 0
  Test::DZil: 0
  Test::More: 0
  version: 0
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Test-DiagINC
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Dist::Zilla::Plugin::Test::DiagINC:
    file: lib/Dist/Zilla/Plugin/Test/DiagINC.pm
    version: 0.001
requires:
  Dist::Zilla::Role::FileFinderUser: 0
  Dist::Zilla::Role::FileMunger: 0
  Dist::Zilla::Role::PPI: 0
  Dist::Zilla::Role::PrereqSource: 0
  Moose: 0
  PPI: 0
  Syntax::Keyword::Junction: 0
  namespace::autoclean: 0
  perl: 5.008001
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dagolden/Dist-Zilla-Plugin-Test-DiagINC/issues
  homepage: https://github.com/dagolden/Dist-Zilla-Plugin-Test-DiagINC
  repository: https://github.com/dagolden/Dist-Zilla-Plugin-Test-DiagINC.git
version: 0.001
x_authority: cpan:DAGOLDEN
